wandb:
  project: murata_exp
  exp_num: 1
  tags: [bert]
path:
  data_file_name: /content/drive/MyDrive/murata_labo_exp/data/livedoor_sentence.csv
  checkpoint_path: checkpoints
model:
  d_model: 768
  n_classes: 3
  max_length: 512
training:
  val_test_size: 0.3
  test_size: 0.15
  n_epochs: 2
  seed: 40
  batch_size: 32
  learning_rate: 0.0001
  text_column_name: sentence
  label_column_name: label
callbacks:
  patience: 3
  patience_min_delta: 0
