wandb:
  project: murata_exp
  exp_num: 3
  tags: [bert]
path:
  data_file_name: /content/drive/MyDrive/murata_labo_exp/data/binary_classification_chunkover5.csv
  test_file_name: /content/drive/MyDrive/murata_labo_exp/data/binary_classification_chunkover5_test.csv
  checkpoint_path: checkpoints
model:
  d_model: 768
  hidden_size: 16
  max_length: 512
training:
  train_size: 0.8
  n_epochs: 4
  seed: 40
  batch_size: 32
  max_length: 64
  learning_rate: 0.0001
  text_column_name: sentence
  label_column_name: label
callbacks:
  patience: 3
  patience_min_delta: 0
